version: '3.3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: suite_backend_api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - insurance_suite
    volumes:
      - static_volume:/home/app/web/api/staticfiles
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: suite_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks: 
      - insurance_suite

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/api/staticfiles
    ports:
      - 80:80
    networks:
      - insurance_suite
    depends_on:
      - web

networks:
  insurance_suite:

volumes:
  postgres_data:
  static_volume: