version: '3.3'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: suite_backend_api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    networks:
      - insurance_suite
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: suite_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks: 
      - insurance_suite

networks:
  insurance_suite:

volumes:
  postgres_data:
  static_volume: